### ISSUE TITLE
can you please add sharing options when an image is clicked on ?( now we only have download and close)

### ISSUE THREAD

**Issue by heitumo** [hbstack/bigger-picture#14]
<img width="984" alt="image" src="https://user-images.githubusercontent.com/12490954/232253955-6d5a5461-cdad-4777-831f-a1266c3485a5.png">

Maybe we can have options of sharing the image to twitter/wechat/weibo/FB/ins ? Thank you again.

**Comment by razonyang** [comment]
Didn't have experience about sharing images, could you please explain it in detail?

1. Which URL should be used as the share link? 
2. What do you expect when clicking the share link?

Please note that there aren't pages for a single image, they are belonged to the posts or albums.

**Comment by heitumo** [comment]
1.   when we want to share 
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/12490954/232265283-5b1f3710-46ed-49bf-a749-6110d201a278.png"> 

we could just share the URL of  https://hb-theme.hugomods.com/en/blog/2023/03/tutorial/ 

2. Expect when clicking the share link, it could be just the post link that displays the image OR the link of the image. 
    ( maybe sharing the post link is a better way to go since it include the image and the content)

Found Hugo + photo swipe  
<img width="376" alt="image" src="https://user-images.githubusercontent.com/12490954/232265050-b50b22f7-020e-4370-951c-5bb77e04a0af.png">

<img width="624" alt="image" src="https://user-images.githubusercontent.com/12490954/232265024-61745410-de8e-432f-ab71-938952f39870.png">


this is achievable with Hugo and photoswipe  (https://www.liwen.id.au/heg/) and beautifulhugo themes 
Thank you for the quick response.

**Comment by razonyang** [comment]
The example of liwen, it doesn't display the image I want to share (uses Logo instead). Is that expected?

You could share the image to tweet and see what's happen.

**Comment by razonyang** [comment]
Just did some research, I think it's impossible.

For example, the twitter cards use page's `twitter:image` meta tag.

> See https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image.

But we won't/unable to generate pages for every single image, so when we're sharing the image, the post's thumbnail instead of the one we want to share will be shown.

**Comment by heitumo** [comment]
> Just did some research, I think it's impossible.
> 
> For example, the twitter cards use page's `twitter:image` meta tag.
> 
> > See https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image.
> 
> But we won't/unable to generate pages for every single image, so when we're sharing the image, the post's thumbnail instead of the one we want to share will be shown.
> 
> EDIT: That makes sense for featured image only, since the featured image will be shown, there will be no ambiguity.

yes, even for Gallery images, we can show featured images? Not sure how it works under the hood comparing to featured image of a post,  but an image is better than no image  Thank you.

**Comment by razonyang** [comment]
> we can show featured images? 

Yes, it's implemented already, except the _share_ button.

It may take time to implement, need to modularize this functionality, so that it can be reused in other places (not for image viewer only, the share button could be placed in content panel next or above/below the post content).

I couldn't give ETA, I'll start on it after finished the docs.

**Comment by razonyang** [comment]
Implemented by #16, see https://hbstack.dev/en/docs/modules/gallery/overview/#album-social-share-image for detail.

Thanks for your idea.
